PRIMITIVES_TYPES = ("ZEROGRADIENT", "SYMMETRY", "PERIODIC", "INACTIVE",
                    "WALL", "ISOTHERMALWALL", "MASSTRANSFERWALL",
                    "ISOTHERMALMASSTRANSFERWALL", "DIRICHLET", "NEUMANN","ISOTHERMALDISTURBANCEWALL",
                    "ISOTHERMALBEAVERJOSEPHWALL","BEAVERJOSEPHWALL",
                    "ISOTHERMALJJPOROUSWALL","JJPOROUSWALL",
                    "ISOTHERMALGENERALVWALL","GENERALVWALL",
                    "ISOTHERMALOPPOSITIONUPWALL","OPPOSITIONUPWALL",
                    "ISOTHERMALOPPOSITIONLOWWALL","OPPOSITIONLOWWALL",
                    "ISOTHERMALJJPOROUSUPWALL","JJPOROUSUPWALL",
                    "ISOTHERMALJJPOROUSLOWWALL","JJPOROUSLOWWALL")
LEVELSET_TYPES = ("ZEROGRADIENT", "SYMMETRY", "PERIODIC", "INACTIVE",
                  "DIRICHLET", "REINITIALIZATION")

EDGE_TYPES = (
    "PERIODIC_ANY", "ANY_PERIODIC",
    "SYMMETRY_ANY", "ANY_SYMMETRY")

VERTEX_TYPES = (
    "PERIODIC_ANY_ANY", "ANY_PERIODIC_ANY", "ANY_ANY_PERIODIC",
    "SYMMETRY_ANY_ANY", "ANY_SYMMETRY_ANY", "ANY_ANY_SYMMETRY")